# Generated by Django 4.2 on 2026-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0002_medication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='pill_color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('MULTI-COLOR', 'Multi-color')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pill_imprint',
            field=models.CharField(blank=True, help_text='Text/numbers on pill', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='pill_shape',
            field=models.CharField(blank=True, choices=[('ROUND', 'Round'), ('OVAL', 'Oval'), ('CAPSULE', 'Capsule'), ('SQUARE', 'Square'), ('DIAMOND', 'Diamond')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pill_size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small (<10mm)'), ('MEDIUM', 'Medium (10-15mm)'), ('LARGE', 'Large (>15mm)')], max_length=10, null=True),
        ),
    ]
