# Generated by Django 4.2 on 2026-02-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0003_medication_pill_color_medication_pill_imprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('pin_hash', models.CharField(max_length=255)),
                ('accessed_by_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('medications_accessed', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.IntegerField()),
                ('warning_message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_warnings', to='medical_inventory.astronaut')),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_logs', to='medical_inventory.astronaut')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_inventory.medication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicationThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(help_text='Maximum units per day')),
                ('single_dose_limit', models.IntegerField(help_text='Maximum units per single withdrawal')),
                ('warning_percentage', models.IntegerField(default=80, help_text='Percentage of limit to trigger warning')),
                ('medication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='medical_inventory.medication')),
            ],
        ),
        migrations.AddIndex(
            model_name='warninglog',
            index=models.Index(fields=['-timestamp'], name='medical_inv_timesta_fc5e87_idx'),
        ),
        migrations.AddIndex(
            model_name='warninglog',
            index=models.Index(fields=['astronaut', '-timestamp'], name='medical_inv_astrona_0e3520_idx'),
        ),
    ]
