# Generated by Django 5.1.1 on 2026-02-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0005_astronaut_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronaut',
            name='photo',
        ),
        migrations.AddField(
            model_name='astronaut',
            name='photos',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
