# Generated by Django 5.1.1 on 2026-02-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0006_remove_astronaut_photo_astronaut_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronaut',
            name='photos',
        ),
        migrations.AddField(
            model_name='astronaut',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='astronaut_photos/'),
        ),
    ]
