# Generated by Django 5.1.1 on 2026-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0007_remove_astronaut_photos_astronaut_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
