# Generated by Django 5.1.1 on 2026-02-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0008_alter_astronaut_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('PAINRELIEF', 'Pain Relief'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTINAUSEA', 'Anti-Nausea'), ('SLEEP_AID', 'Sleep Aid'), ('ALLERGY', 'Allergy'), ('STIMULANT', 'Stimulant'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
