# Generated by Django 5.2.11 on 2026-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0010_accesslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslogitem',
            name='access_log',
        ),
        migrations.RemoveField(
            model_name='accesslogitem',
            name='medication',
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('ANALGESIC', 'Pain Relief'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTINAUSEA', 'Anti-Nausea'), ('SLEEP_AID', 'Sleep Aid'), ('ALLERGY', 'Allergy'), ('STIMULANT', 'Stimulant'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='AccessLogItem',
        ),
    ]
