# Generated by Django 5.2.11 on 2026-02-27 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0011_remove_accesslogitem_access_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('UNLOCK', 'Unlock'), ('RESTOCK', 'Restock')], default='UNLOCK', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('door_open_seconds', models.IntegerField(blank=True, help_text='Seconds the door was open (unlocks only)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('astronaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='medical_inventory.astronaut')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccessLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('access_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_inventory.accesslog')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_inventory.medication')),
            ],
        ),
    ]
